server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${MY_DB:localhost:15432}/my_db?ssl=false
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

delete.user.directory.url: ${FILE_S:localhost:8080}/file/deleteUserDirectory/