server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${MY_DB:localhost:15432}/my_db?ssl=false
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 5MB
      max-request-size: 5MB

file.upload.dir: D:\\storage\\





